name = "image-server"
main = "./build/worker.mjs"
compatibility_date = "2024-04-15"

[build]
command = "make build"

[[d1_databases]]
binding = "D1_DATABASE"
database_name = "image-server"
database_id = "440922e9-98b8-4512-81c4-5f32094844cf"
